### ISSUE TITLE
update balena-os/jetson-flash to v0.5.51

### ISSUE THREAD

**Issue by dremsol** [pgils/docker-jetson-flash#116]

**Comment by pgils** [comment]
Done: #117 . Would you be able to test with a `jetson-orin` device @dremsol ?

**Comment by dremsol** [comment]
Currently we have the Jetson Orin Nano DevKit equipped with NVME ssd (`jetson-orin-nano-nvme`) device to test with. However, this is a different flashing procedure as we are used to for the t210 and t194 devices. Please check the [Orin_Nx_Nano_NVME](https://github.com/balena-os/jetson-flash/tree/ace028d92541fdf25c3d0723aacb5144fda2c904/Orin_Nx_Nano_NVME) upstream which containers it's own isolated Dockerfile.

**Comment by dremsol** [comment]
tag v0.38.0 results in following output when flashing a `jetson-nano-emmc` device
```
 ./djetson-flash -m jetson-nano-emmc -f ~/balena-images/balena-cloud-hwky-dart-production-nano-jetson-nano-emmc-2.112.13-v14.9.1.img.zip -p
Unable to find image 'ghcr.io/pgils/docker-jetson-flash:v0.38.0' locally
docker: Error response from daemon: manifest unknown.
See 'docker run --help'.
```
