### ISSUE TITLE
missing tags from registry

### ISSUE THREAD

**Issue by dremsol** [pgils/docker-jetson-flash#126]
some tags are missing from registry (v0.38.0, v0.38.1) when checking out tag v0.38.2 `djetson-flash` tries to pull tag `0.38.100`
```
➜  docker-jetson-flash git:(v0.38.2) ./djetson-flash
Unable to find image 'ghcr.io/pgils/docker-jetson-flash:v0.38.100' locally
```

**Comment by pgils** [comment]
hi @dremsol, this was the result of some changes in the authentication used in the actions workflows (#125).

Should be fixed now with v0.41.0.
