### ISSUE TITLE
support MacOs Big Sur

### ISSUE THREAD

**Issue by dremsol** [pgils/docker-jetson-flash#24]
Currently the tool doesn't run on stock MacOS Big Sur. At a minimum it requires updating `bash` through `homebrew` and supporting BSD commond line tools such as `readline`.

**Comment by dremsol** [comment]
`brew install coreutils` and interchange `readline` by `greadline` runs the container. However, USB passthrough with Docker on MacOS is problematic.

**Comment by pgils** [comment]
Hi @dremsol . USB does seem to be an issue for Docker on macOS/Windows. The solutions you linked looks like it would work. Note that it would cause the USB device to always connect to the VM, so if you need to connect to the serial port of the device via USB you would probably need to stop the VM first.

I like the idea of dropping the GNU coreutils dependency. I think the only GNU specific command is `readlink -e` which could be replaced by something like a `readlink -f` && `test -e`. I'll look into this.

**Comment by dremsol** [comment]
Indeed, both [Windows](https://docs.docker.com/desktop/faqs/#can-i-pass-through-a-usb-device-to-a-container)/MacOS will give problems with usb pass through. At least it wont make things easier. Maybe only support Linux at the moment.
