### ISSUE TITLE
rootfs size

### ISSUE THREAD

**Issue by dremsol** [pgils/docker-jetson-flash#28]
Do we need to set a rootfs size for default BalenaOS images? If we do, don't we end up in trouble when updating BalenaOS through BalenaCloud?

**Comment by pgils** [comment]
Hi @dremsol

The `-s, --size` argument is optional and intended for development/testing use. It can be used to match an increased `IMAGE_ROOTFS_SIZE` (like in https://github.com/hwkyai/balena-jetson/commit/42c427b35d076bb13f3bfffd359bc8febf3b5e63 for example). 

The rootfs for Balena cloud images will likely always fit in the default size set by [jetson-flash](https://balena-os/jetson-flash) so the `--size` argument is not needed. And like you said, a rootfs size that does not match `IMAGE_ROOTFS_SIZE` in [balena-jetson](https://github.com/balena-os/balena-jetson) will probably cause update issues.
